### ISSUE TITLE
failing to start Overtone with internal SuperCollider server under Ubuntu

### ISSUE THREAD

**Issue by ghost** [overtone/overtone#133]
Hi,

Trying to start overtone under Ubuntu, I get the following trace:

<pre>
user=> (use 'overtone.live)
--> Loading Overtone...
--> Please boot a server to start making noise:
    * (boot-server)             ; boot default server (honours config)
    * (boot-internal-server)    ; boot an internal server
    * (boot-external-server)    ; boot an external server
    * (connect-external-server) ; connect to an existing external server

--> Booting internal SuperCollider server...
setting up worldoptions
Warning - native sc-arg :mSharedControls was nil
--> Connecting to internal SuperCollider server...
--> Connection established
Exception The following deps took too long (10000 seconds) to be satisfied: :server-ready  overtone.libs.deps/wait-until-deps-satisfied (deps.clj:154)

user=> 
</pre>

Yet the supercollider server appears to be starting; here is the JACK log:

<pre>
20:43:54.964 Changement des connexions JACK.
Thu Aug  9 20:43:54 2012: New client 'SuperCollider' with PID 4499
20:44:04.999 Changement du graphique des connexions JACK.
20:44:05.208 Changement du graphique des connexions JACK.
20:44:05.435 Changement du graphique des connexions JACK.
Thu Aug  9 20:44:04 2012: New client 'lsp' with PID 4568
Thu Aug  9 20:44:04 2012: Client 'lsp' with PID 4568 is out
Thu Aug  9 20:44:05 2012: New client 'jack_connect' with PID 4572
Thu Aug  9 20:44:05 2012: Connecting 'SuperCollider:out_1' to 'system:playback_1'
Thu Aug  9 20:44:05 2012: Client 'jack_connect' with PID 4572 is out
Thu Aug  9 20:44:05 2012: New client 'jack_connect' with PID 4575
Thu Aug  9 20:44:05 2012: Connecting 'SuperCollider:out_2' to 'system:playback_2'
Thu Aug  9 20:44:05 2012: Client 'jack_connect' with PID 4575 is out
Thu Aug  9 20:44:05 2012: New client 'jack_connect' with PID 4578
Thu Aug  9 20:44:05 2012: Connecting 'system:capture_1' to 'SuperCollider:in_1'
Thu Aug  9 20:44:05 2012: Client 'jack_connect' with PID 4578 is out
Thu Aug  9 20:44:05 2012: New client 'jack_connect' with PID 4581
Thu Aug  9 20:44:05 2012: Connecting 'system:capture_2' to 'SuperCollider:in_2'
Thu Aug  9 20:44:05 2012: Client 'jack_connect' with PID 4581 is out
</pre>

Any help/hints much appreciated

**Comment by frenchy64** [comment]
This should be closed since we don't support internal servers any longer.
