### ISSUE TITLE
JVM crashes while booting up overtone

### ISSUE THREAD

**Issue by tech-Nico** [overtone/overtone#236]
After the last git pull, I'm getting the following JVM crash when executing (use 'overtone.live) on Ubuntu 13.04 64bits

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f0ec9106671, pid=5337, tid=139699517339392

 JRE version: 7.0_09-b05
 Java VM: Java HotSpot(TM) 64-Bit Server VM (23.5-b02 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [ld-linux-x86-64.so.2+0x15671]  _dl_make_stack_executable+0x27e1

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/nicoletto/dev/clojure/libs/overtone/overtone/hs_err_pid5337.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Found 0 LADSPA plugins
**\* ERROR: dlsym load err '/home/nicoletto/dev/clojure/libs/overtone/overtone/native/linux/x86_64/libscsynth.so: undefined symbol: load'
**\* ERROR: dlsym load err '/home/nicoletto/dev/clojure/libs/overtone/overtone/native/linux/x86_64/libjogl.so: undefined symbol: load'
**\* ERROR: dlopen '/home/nicoletto/dev/clojure/libs/overtone/overtone/native/linux/x86_64/libjogl_awt.so' err 'libjawt.so: cannot open shared object file: No such file or directory'
Exception in thread "Thread-1" java.net.SocketException: The transport's socket appears to have lost its connection to the nREPL server
      transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
      transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
      transport.clj:42 clojure.tools.nrepl.transport/fn-transport[fn]
         core.clj:1836 clojure.core/binding-conveyor-fn[fn]
           AFn.java:18 clojure.lang.AFn.call
      (Unknown Source) java.util.concurrent.FutureTask$Sync.innerRun
      (Unknown Source) java.util.concurrent.FutureTask.run
      (Unknown Source) java.util.concurrent.ThreadPoolExecutor.runWorker
      (Unknown Source) java.util.concurrent.ThreadPoolExecutor$Worker.run
clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 134}
      (Unknown Source) java.lang.Thread.run
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.eval$fn__1965.invoke(eval.clj:214)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:283)Bye for now!
    at leiningen.repl$start_server.invoke(repl.clj:104)
    at leiningen.repl$server$fn__4422.invoke(repl.clj:172)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$bound_fn_STAR_$fn__4102.doInvoke(core.clj:1810)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Unknown Source)

**Comment by dfuenzalida** [comment]
I ran into this issue today with Ubuntu 14.04 64-bit and after a while I stumbled into this StackOverflow question: http://askubuntu.com/q/320946/77438 which I think is related to this issue.

I installed the `jackd2` package and then I listed the devices compatible with ALSA using `aplay -l` to get the parameters to use Jack. In my laptop, the card #1 and device #0 is the analog sound jack where I plug my headphones, thus I start a new terminal and run `jackd -R -d alsa -d hw:1,0` on it.

After that, I was able to run the examples and also the Golberg variations example from https://github.com/ctford/goldberg which uses Overtone and Leipzig.

For the record, I'm using this project.clj:

```
(defproject goldberg "0.1.0-SNAPSHOT"
  :description "The Goldberg Variations in Overtone."
  :dependencies	[
    [org.clojure/clojure "1.8.0"]
    [leipzig "0.10.0" :exclusions [org.clojure/clojure]]
    [overtone "0.9.1" :exclusions [org.clojure/clojure]]])
```

**Comment by shlomiv** [comment]
Just reporting that I got the same problem today as well on overtone "0.10.3". A bunch of similar error messages and a JVM crash at the end (the same as in earlier posts: `[libscsynth.so+0x220dc]  SC_UdpInPort::SC_UdpInPort(World*, int)+0x9c`)

Tried installing supercollider and starting the server there, and that does not work as well, I am getting:

> booting 57110
> jackdmp 1.9.11
> Copyright 2001-2005 Paul Davis and others.
> Copyright 2004-2014 Grame.
> jackdmp comes with ABSOLUTELY NO WARRANTY
> This is free software, and you are welcome to redistribute it
> under certain conditions; see the file COPYING for details
> JACK server starting in realtime mode with priority 10
> self-connect-mode is "Don't restrict self connect requests"
> audio_reservation_init
> Acquire audio card Audio0
> creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
> could not initialize audio.
> RESULT = 1
> ERROR: server failed to start
> For advice: [http://supercollider.sf.net/wiki/index.php/ERROR:_server_failed_to_start]

Went to that last link for advice and all it said was that there might already be a process active and to kill it. There were no other process running.
