### ISSUE TITLE
Using scope on 64 bit Fedora crashes JVM

### ISSUE THREAD

**Issue by plewto** [overtone/overtone#245]
(defsynth foo [freq 440](out:ar 0 %28sin-osc:ar freq%29))
(foo)
(scope :audio-bus 0)
# A fatal error has been detected by the Java Runtime Environment:
# 
# SIGSEGV (0xb) at pc=0x0000003683e09b20, pid=7380, tid=140407911237376
# 
# JRE version: 7.0_25
# Java VM: OpenJDK 64-Bit Server VM (23.7-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x9b20]  pthread_mutex_lock+0x0
# 

Fedora 17 64-bit

**Comment by mattearnshaw** [comment]
this is still an issue.
