### ISSUE TITLE
Update clj-native dependency to 0.9.5

### ISSUE THREAD

**Issue by rogerallen** [overtone/overtone#306]
Forgot to file this bug earlier.  With the latest clj-native at version 0.9.5, Overtone now works on ARM.  See the discussion around August 6, 2014 here:  https://groups.google.com/forum/?fromgroups#!topic/overtone/53jRQWBy4Rw

**Comment by rudle** [comment]
@rogerallen this issue still seems to be valid. Are you interested in opening a PR with the dependency change? That's probably the best way to move the discussion forward.

**Comment by rogerallen** [comment]
It is a one character change to the project.clj.  I sincerely doubt the lack of the PR is the holdup here.

**Comment by rogerallen** [comment]
Just browsing the source, I see this was resolved.  Closing.

https://github.com/overtone/overtone/blob/master/deps.edn#L14
         clj-native {:mvn/version "0.9.5"}
