### ISSUE TITLE
Incorrectness in Metronomes

### ISSUE THREAD

**Issue by seewalker** [overtone/overtone#308]
In my environment (overtone 0.9.1, clojure 1.5.1, OSX 10.9.4),  Metronome vars do not correctly determine the timestamp of beats. Because the overtone code involved in metronomes is so simple and because it works fine on other systems, it unlikely the problem. There is probably some supercollider issue here. What might the steps to figuring it out be? And is it a problem that ought to be caught as an error in overtone's metronome implementation?

Here's a transcript of the issue:

```
clojure.test.mode> (def met (metronome 70))
#'clojure.test.mode/met
clojure.test.mode> (met)
7
clojure.test.mode> (met)
9
clojure.test.mode> (met :bpm)
70
clojure.test.mode> (met 0)
1.412993447113E12
clojure.test.mode> (met 1)
1.4129934479701428E12
clojure.test.mode> (met 2)
1.4129934488272856E12
clojure.test.mode> (map met (range 20))
(1.412993447113E12 1.4129934479701428E12 1.4129934488272856E12 1.4129934496844285E12 1.4129934505415715E12 1.4129934513987144E12 1.4129934522558572E12 1.412993453113E12 1.4129934539701428E12 1.4129934548272856E12 1.4129934556844285E12 1.4129934565415715E12 1.4129934573987144E12 1.4129934582558572E12 1.412993459113E12 1.4129934599701428E12 1.4129934608272856E12 1.4129934616844285E12 1.4129934625415715E12 1.4129934633987144E12)
```

**Comment by kaze** [comment]
I propose closing this issue if @seewalker has no further comments on it.

**Comment by seewalker** [comment]
No recollection of what I was talking about all those years ago, yes by all means.
