### ISSUE TITLE
Encountering an exception upon (use 'overtone.live)

### ISSUE THREAD

**Issue by chrissound** [overtone/overtone#315]
Hi everyone,

I started off by running:  `lein new insane-noises`
Then edited project.clj to include the overtone dependency: `:dependencies [[org.clojure/clojure "1.6.0"],[overtone "0.9.1"]]`

```
user=> (use 'overtone.live)
--> Loading Overtone...
  ********************************************************** 
       WARNING: JVM argument TieredStopAtLevel=1 is active, and may 
       lead to reduced performance. This happens to currently be the 
       default lein setting:

       https://github.com/technomancy/leiningen/pull/1230

       If you didn't intend this JVM arg to be specified, you can turn 
       it off in your project.clj file or your global 
       ~/.lein/profiles.clj file by adding the key-val

       :jvm-opts ^:replace [] 
       ********************************************************** 

CompilerException java.lang.Exception: Can't connect to native server - no compatible libraries for your system are available., compiling:(overtone/live.clj:4:38)
```

**Comment by exclamaforte** [comment]
I'm having the exact same problem.

**Comment by chrissound** [comment]
No luck, still getting that error. Jack server is definitely running as far as I can see. I've tried starting it via command line as well as via qjackctl.

**Comment by chrissound** [comment]
I managed to get somewhat further by trying an 'external' server, 

Starting jack: jackd -R -d alsa -d hw:0 -r 44100
Starting supercollider: scsynth -u 57110

And then: lein repl (connect-external-server 57110):

--> Connecting to external SuperCollider server: 127.0.0.1:57110
--> Connection established
:happy-hacking

**Comment by hlolli** [comment]
Native libraries (which I don't recommend using) are only available for:
64 bit linux (not 32bit)
64 and 32 bit MacOsX
32 bit windows.

Perhaps you were running on some of the non supported platforms?

That aside I highly recommend using your own Supercollider and use connect to external-server, either manually or add it into your overtone configuration file to do ti automatically.
(I close this but will open again if this is still a problem).
