### ISSUE TITLE
freesound function triggers sound twice

### ISSUE THREAD

**Issue by ormf** [overtone/overtone#318]
In the current commit on github (0c626635e4ecd7c8a392eb572318705e654b0b6f as of Thu Nov 20 09:15:30 2014 +0000) the freesound function seems to trigger two sounds (ca. 0.2 secs apart), like in the following code:

=>(use 'overtone.live)
=>(def cl-hat (freesound 802))
=>(cl-hat)

This doesn't happen using the overtone 0.9.1 release. This behaviour has been confirmed by Roger Allen so it seems to affect others as well.

**Comment by ormf** [comment]
Hunted down the problem: The first breaking change appears at commit ba611e982890412acaa497ab6d28a4673b15abab (2014-01-23 15:33:21, "Replace default buffer players with a new design capable of playing parts")

After that change freesound samples get played back three times.

The second change happens in commit 6be4ea83a93769855e83117127250f9632f567ca (2014-01-23 16:14:33, "Tweak rate of ugens to fix non looping behaviour").

After that change, freesound samples are played back two times.

**Comment by ormf** [comment]
The problem lies in the definitions of mono-partial-player and stereo-partial-player: Since the buffer is read out with a looping phasor, the default release time leads to a wrap-around to the beginning seemingly retriggering the sound if it is a percussive sample. For now a simple fix would be to set the default release time in the synthdef to 0.

**Comment by ckuttruff** [comment]
Encountered this issue as well.  Fine in 0.9.1, but I heard this sound distortion on the latest master.

**Comment by awwaiid** [comment]
I'm running the version in master so I can get the new freesound API, and am also having this wrap-around issue.

**Comment by awwaiid** [comment]
doing git revert ba611e982890412acaa497ab6d28a4673b15abab "fixed" it.
