### ISSUE TITLE
Freesound assets non cached across projects?

### ISSUE THREAD

**Issue by ckuttruff** [overtone/overtone#324]
I'm noticing that the "sampled-piano" synth, which I used it one project, was being downloaded again in a separate project directory.

Noticing paths in my `.overtone/assets/` dir are almost identical besides the hash:
```
www.freesound.org-api-sounds-148401api_key47efd585321048819a2328721507ee23--1007255502
www.freesound.org-api-sounds-148401api_key47efd585321048819a2328721507ee23--1441292287
www.freesound.org-api-sounds-148401-serveapi_key47efd585321048819a2328721507ee23---579650354
www.freesound.org-api-sounds-148401-serveapi_key47efd585321048819a2328721507ee23--98019573
```
This logic seems to come from here (but still sorting out why the hash changes for what should be an identical url):
https://github.com/overtone/overtone/blob/master/src/overtone/libs/asset.clj#L48

Am I missing something obvious here, or have others run into this caching issue as well?

Thanks!

**Comment by samaaron** [comment]
If I remember correctly, this was triggered by internal changes between Clojure versions, but I may be mistaken. However, this is the least of the concerns as Freesound will be shutting off the version of the API that Overtone uses imminently. So unless someone adds support for the new API, freesound support will sadly stop working...

**Comment by ckuttruff** [comment]
oh, brutal :(  
Thanks for the heads up.  Maybe I'll look into that as a potential project... certainly very useful to be able to grab samples from there.

I'll go ahead and close this, but I'll try to poke around a bit to see why this hashing is off.

Thanks for the quick reply
