### ISSUE TITLE
Freesound piano samples not working

### ISSUE THREAD

**Issue by petermcculloch** [overtone/overtone#335]
Freesound says that its APIv1 is no longer supported and that it needs to move to version 2.  

Here's the error message:
http://www.freesound.org/api/sounds/148503/?api_key=47efd585321048819a2328721507ee23

**Comment by harold** [comment]
Perhaps issue #333 interests you, then.

Hope that helps.

**Comment by LaloHao** [comment]
Were you able to fix it? @petermcculloch 
I did the steps on #333 specifically https://github.com/overtone/overtone/issues/333#issuecomment-126501059
But for some reason it stills seems to be trying to use the old api

**Comment by cldwalker** [comment]
This has been fixed on master with #332. Until a release is cut you can checkout this project, `lein install` and use `[overtone "0.10-SNAPSHOT"]` in your project

**Comment by cicerojones** [comment]
Updating the version of overtone that I was using in my project (as stated in [installing overtone section](https://github.com/overtone/overtone/wiki/Installing-overtone], this was"0.10.1" as of July 2016)) solved this problem for me as well. I just had to find my Freesound account password info.

(For those whom these things are a burden--perhaps this issue can be closed?)
