### ISSUE TITLE
Authorisation issue for freesound using vim-fireplace

### ISSUE THREAD

**Issue by richashworth** [overtone/overtone#337]
On downloading a sample for the first time, it seems I am required to authorise Overtone with my freesound account. A browser is opened, providing an authorization code. I am using vim-fireplace to trigger the sample's download, but it isn't clear how the code should be passed into overtone. I have tried pasting it into the repl, but this did not work. Any help greatly appreciated.

**Comment by namin** [comment]
The code uses `(read-line)` to get the access token from stdin. Is there a way for you to write to stdin?

**Comment by jtbeckha** [comment]
FWIW it works in fireplace for me if I pull a sample down in the REPL first.
i.e. (in the REPL)
`(use 'overtone.live)
(def test (freesound-sample 1))`

**Comment by jtbeckha** [comment]
^Wish there was a way to automate that though, it's a bit of a pain even if you're coding in the REPL.  Wonder if it would be practical to scrape the code off of the freesound authorization page, or optionally allow authentication via a token instead of OAuth (as described [here](https://www.freesound.org/docs/api/authentication.html#token-authentication))?

**Comment by namin** [comment]
I agree it's a pain... Sadly, tokens don't work for downloading sound.

**Comment by jeffswitzer** [comment]
I'm also having trouble copying the auth code to the repl. I try the following steps from a termite terminal on arch linux - clojure 1.8.0 overtone 0.10.1.
```
lein repl
(use 'overtone.live)
(def test (freesound-sample 1))
```

At which point the browser opens I log in to get the authcode, and the repl is displaying:
```
--> Asset not cached - starting download...
Authorize in browser and paste code in Stdin.
https://www.freesound.org/apiv2/oauth2/authorize/?client_id=ea6297be42e9de76d47c&response_type=code
```

However i can't type or paste anything in. How can i get the auth code into stdin?

**Comment by namin** [comment]
If you do `lein repl`, then `(read-line)` -- can you actually type a line of text and get it echoed?

**Comment by jeffswitzer** [comment]
Yeah (read-line) echos the text I type in correctly.

It seems like the repl just becomes irresponsive after the authcode request because if I try to type anything in the characters I type aren't even displayed. If I run top at this point the cpu usage isn't high or anything.

**Comment by namin** [comment]
Thanks for the feedback. Very strange. Since I cannot reproduce, it's difficult for me to fix this.
Is it maybe the browser opening that freezes the repl?
Let me know if you have further info or suggestions.

**Comment by jeffswitzer** [comment]
Your intuition was correct :) If I open the browser first everything works fine. The browser in use for this test was firefox.

**Comment by Psykopear** [comment]
same for google-chrome on archlinux with gnome-terminal, opening the browser first "solves" the problem

**Comment by cbcoutinho** [comment]
This is still an issue using `vim-fireplace` in parallel with a headless `lein ` instance via `lein trampoline repl :headless &`. When I open an example from the `overtone` repo, my browser is opened, but i have no way to getting the access code back into `vim`.
