### ISSUE TITLE
More Getting Started Explanation

### ISSUE THREAD

**Issue by ccorcos** [overtone/overtone#343]
I'm going through [this stuff](https://github.com/overtone/overtone/blob/master/src/overtone/examples/getting_started/basic.clj) and it blows my mind that these functions make these sounds. I find it incredibly hard to understand in my head how the hell this function creates the associated sound:

``` clj
(definst overpad [note 60 amp 0.7 attack 0.001 release 2]
  (let [freq  (midicps note)
        env   (env-gen (perc attack release) :action FREE)
        f-env (+ freq (* 3 freq (env-gen (perc 0.012 (- release 0.1)))))
        bfreq (/ freq 2)
        sig   (apply +
                     (concat (* 0.7 (sin-osc [bfreq (* 0.99 bfreq)]))
                             (lpf (saw [freq (* freq 1.01)]) f-env)))]
    (* amp env sig)))
```

I'd love to learn more about the thought that went into making this synth. How does it work? What's really going on here? How do you apply this thinking to making other sounds?

Thanks!

**Comment by pjagielski** [comment]
Hi. I agree with you that Overtone has really steep learning curve and needs more tutorials. I don't know if you are familiar with synthesis, SuperCollider or Clojure (which itself is not a self-explaining language...). This synth design is not straightforward, I enourage you to start with something simpler. I have some basics explained in [this tutorial](https://github.com/pjagielski/overtone-workshop/blob/master/src/overtone_workshop/sounds.clj), you can find some more tutorials on github.

In short:
- the base are two oscillators: `sin-osc` and `saw`
- `sin-osc` frequency (`breq`) value is 1 octave below input note `(/ freq 2)`
- second oscillator is filtered by low-pass filter (`lpf`) with percussive style (`perc`) envelope (`f-env`) - this means that the filter amount moves down from `4 * freq` to `freq` value
- first oscillator's amplitude is reduced by to 0.7 by just multiplying the signal (`* 0.7`)
- oscillators are mixed together by adding them: `apply +` which is in short equal to sin1 + sin2
- another envelope (`env`) is applied to resulting sound - so sound's amplitude rise quickly (`attack` is 0.001 second) and falls shortly (`release` is 2 seconds)

I hope it's a bit more clear now...

**Comment by ccorcos** [comment]
interesting. thanks for the explanation -- this part still makes no sense to me though: 

```
f-env (+ freq (* 3 freq (env-gen (perc 0.012 (- release 0.1)))))
```

What do you get when you mutiply a frequency times an envelope??

**Comment by pjagielski** [comment]
I guess the idea here is something called "keytracking". It means that the filter cutoff frequency is lower for lower notes and higher for higher notes. So that's why `freq` is used to determine the cutoff frequency. Multiplying just "applies" the envelope to the cutoff, so the starting cutoff is `freq`, then it goes up to `freq + 3 * freq` and then goes again down to `freq` value after.

**Comment by ccorcos** [comment]
hmm. so from your explanation, it sounds like we're bascially multiuplying the envelope with a bandpass filter? It still seems really off that this is the second argument to the lpf...

```
(lpf wave f-env)
```

**Comment by hlolli** [comment]
Good resources:
https://mitpress.mit.edu/books/computer-music-tutorial
https://mitpress.mit.edu/books/supercollider-book
http://www.springer.com/us/book/9783319453682
