### ISSUE TITLE
boot-external-server not working

### ISSUE THREAD

**Issue by unhandyandy** [overtone/overtone#353]
I had recently been running SC 3.6 and everything was working fine.  I just upgraded to 3.7 so I could use the sc3-plugins, and now I'm having an odd problem with boot-external-server.  When I initially try that command I get an error saying the connection had failed after 50 attempts.  Then when I try again I get the following, which I believe should be impossible.

```
temperaments.core> (o/server-connected?)
false
temperaments.core> (o/server-connecting?)
false
temperaments.core> (o/boot-external-server)
Exception Can't boot as a server is already connected/connecting!  
overtone.sc.machinery.server.connection/boot/fn--8514 (connection.clj:341)
--> Connection established
```

I am however able to connect to a named port using connect-external-server.

Is this a bug or am I doing something wrong?

**Comment by reiner-dolp** [comment]
Can confirm this behaviour on Win10. Executing the sequence 

```
(use 'overtone.core)
(boot-external-server)
(boot-external-server)
```
results in `Exception Can't boot as a server is already connected/connecting!` for the second call to `boot-external-server`, even though the first call failed. This holds true for the error `Exception Error: unable to connect to externally booted server after 50 attempts` and `Exception Unable to locate a valid scsynth executable on your system`.

---

For reference: Full repl with input and output:

```
user=> (use 'overtone.core)
--> Loading Overtone...
--> Please boot a server to start making noise:
    * (boot-server)             ; boot default server (honours config)
    * (boot-internal-server)    ; boot an internal server
    * (boot-external-server)    ; boot an external server
    * (connect-external-server) ; connect to an existing external server

nil
user=> (boot-external-server)
--> Booting external SuperCollider server...
--> Connecting to external SuperCollider server: 127.0.0.1:35683

Exception Error: unable to connect to externally booted server after 50 attempts.  overtone.sc.machinery.server.connection/external-connection-runner (connection.clj:150)
user=> (boot-external-server)

Exception Can't boot as a server is already connected/connecting!  overtone.sc.machinery.server.connection/boot/fn--4093 (connection.clj:341)
user=>
```

**Comment by gabrielBusta** [comment]
I am experiencing the same issue on Windows 10 Home with SuperCollider 3.7.2

The REPL output is identical to the two examples above.

I replaced SuperCollider with version 3.6.6 and Overtone established the connection just fine. I guess there is a breaking change in the update.

Here is a link to the [external-connection-runner function] (https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/server/connection.clj#L128), aka the main suspect, and here is another link to the [boot function](https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/server/connection.clj#L327) throwing the second exception.

**Comment by samaaron** [comment]
Thanks for reporting the error. Unfortunately I don't have enough time to look into this myself - but if anyone else is prepared to make a pull request containing a fix i'd be very happy to merge it in.

**Comment by frankleonrose** [comment]
@samaaron I have SuperCollider 3.8.0 installed. 

The (elided) help for the command line is
```
/Applications/SuperCollider/SuperCollider.app/Contents/Resources/scsynth
supercollider_synth  options:
   -v print the supercollider version and exit
   -V <verbosity>
          0 is normal behaviour
          -1 suppresses informational messages
          -2 suppresses informational and many error messages
 
```

It looks like Overtone sends "-v 0" for default verbosity, resulting in the immediate exit of the external server.

Is that a change in SC or is Overtone newly sending that option? Want a (trivial, v->V) PR?

**Comment by frankleonrose** [comment]
FYI looks like breaking change occurred in early 2015 as part of SC 3.7.0 https://github.com/supercollider/supercollider/commit/ef88b2647ad00c14189e9a3d5274eae6aa0b1bf1

**Comment by beatboxchad** [comment]
Came here to find-or-open this very issue. It's blocking my work this morning and I'm gonna throw together a little pull request in the next few hours.
