### ISSUE TITLE
lein deps throws java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by dt1** [overtone/overtone#373]
The error I'm getting is:

> Exception in thread "pool-1-thread-1" Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

Not really sure if this is from the overtone install, but I'm able to run other Clojure systems with no issues. I tried installing overtone on the other program and get the same error.

**Comment by dt1** [comment]
So, I explored this one further. First, I changed the overtone dependency to "0.10.0" and that threw this error:

`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f546887bb84, pid=8068, tid=0x00007f540fdff700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b16) (build 1.8.0_111-b16)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b16 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x90b84]  __memcpy_sse2_unaligned_erms+0x1a4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# [do you want the log file?]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/bin/lein: line 396:  8068 Aborted                 (core dumped) "$LEIN_JAVA_CMD" "${BOOTCLASSPATH[@]}" -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -Dmaven.wagon.rto=10000 $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" -Dleiningen.script="$SCRIPT" -classpath "$CLASSPATH" clojure.main -m leiningen.core.main "$@"
`

Then changed the version back to "0.10.1" and this is the new error:

`Could not transfer artifact overtone:overtone:pom:0.10.1 from/to central (https://repo1.maven.org/maven2/): java.security.ProviderException: java.lang.NegativeArraySizeException
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
`

**Comment by hlolli** [comment]
This is strange, how are you defineing overtone as dependency, it's hosted on clojars not maven. Is this solved? If not I'm closing this.

**Comment by dt1** [comment]
Sorry about that. The problem wasn't with overtone, exactly. I needed other things in the system for it all to work. Please close this issue.

**Comment by hlolli** [comment]
Cool !
