### ISSUE TITLE
overtone/at-at is not in central repo

### ISSUE THREAD

**Issue by noxecane** [overtone/overtone#377]
I recently deleted my ~/.m2 directory thanks to hosts of leiningen issues. So when trying to reinstall overtone I was faced with this:
```
Could not find artifact overtone:at-at:jar:1.2.0 in central (https://repo1.maven.org/maven2/)
Could not transfer artifact overtone:at-at:jar:1.2.0 from/to clojars (https://clojars.org/repo/): Read timed out
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
I tried installing the dependency directly and got the same error. Also as a side not, is it safe to use the JVM config in your project.clj to properly setup JVM for overtone

**Comment by hlolli** [comment]
https://clojars.org/overtone/at-at

It's there, downloadable: https://clojars.org/repo/overtone/at-at/1.2.0/at-at-1.2.0.jar

About the project.clj config, it's old but if the user know what he's doing, these settings can be changed or removed. I think the project file will be modernized very soon.

**Comment by noxecane** [comment]
Alright...thanks
