### ISSUE TITLE
:use vs :require in ns declarations

### ISSUE THREAD

**Issue by pbaille** [overtone/overtone#378]
i’m quite new to overtone, while diving into the code, I find navigation quite difficult due to the systematic use of :use in ns declaration, is there any arguments against using “:require :as” instead?

If none, maybe I can help with this.

**Comment by hlolli** [comment]
To get all of overtone core functions without worrying about what's missing or adding a symbol (some prefer to use namespace alias: `(o/demo (o/sin-osc))`

```clojure
(:use overtone.live)
```
same as
```clojure
(:require [overtone.live :refer :all])
```
for individual instruments I would require only the symbols (instruments) you need to use, for example
```clojure
(:require [overtone.inst.sampled-piano :refer [sampled-piano]])
```
We are not making enterprise software here so you are very free to do what you please to make some music.

**Comment by samaaron** [comment]
:-)
