### ISSUE TITLE
Unable to boot the server

### ISSUE THREAD

**Issue by Ex4l** [overtone/overtone#398]
Hello everyone, i was looking to use overtone for fun but i was stuck at booting my internal server. I'm using a Windows 10 64 bits and a 1.8.0_101-b13 JVM.

Here is what i typed based on your wiki found here : https://github.com/overtone/overtone/wiki/Connecting-scsynth

```
D:\dev\projects\tutorial
λ lein deps
D:\dev\projects\tutorial
λ lein repl
nREPL server started on port 52223 on host 127.0.0.1 - nrepl://127.0.0.1:52223
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_101-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'overtone.live)
--> Loading Overtone...

CompilerException java.lang.RuntimeException: Unable to resolve symbol: any? in this context, compiling:(overtone/sc/vbap.clj:183:3)
user=> (use 'overtone.live)
CompilerException java.lang.Exception: No namespace: overtone.sc.vbap found, compiling:(overtone/live.clj:4:1)

user=> (use 'overtone.live)

CompilerException java.lang.Exception: namespace 'overtone.live' not found, compiling:(C:\Users\Ex4l\AppData\Local\Temp\form-init1946623717776860367.clj:1:1)
```

Here is my project/clj if that can help : 

``(defproject tutorial "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"][overtone "0.10.2"] ])``

Have i done any mistake somewhere ? Thanks.

**Comment by hlolli** [comment]
This was my mistake, use clojure version 1.9 or greater in :dependencies until version 0.10.3 gets released.

**Comment by hlolli** [comment]
Overtone 0.10.3 was released, try to run it with clojure 1.8.0 and let me know if you encounter problems,

**Comment by Ex4l** [comment]
I'll try tonight. Thanks for your reactivity.

**Comment by Ex4l** [comment]
Hello, sorry for the delay i wasn't around lately but i tried a simple addition firing my REPL and i got this error :

`λ lein repl
nREPL server started on port 51231 on host 127.0.0.1 - nrepl://127.0.0.1:51231
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_101-b13
Docs: (doc function-name-here)
(find-doc "part-of-name-here")
Source: (source function-name-here)
Javadoc: (javadoc java-object-or-class-here)
Exit: Control+D or (exit) or (quit)
Results: Stored in vars *1, *2, *3, an exception in *e

user=> (+1 2)

ClassCastException java.lang.Long cannot be cast to clojure.lang.IFn user/eval1244 (form-init5802287838241606917.clj:1)`

**Comment by Ex4l** [comment]
Up.

**Comment by hlolli** [comment]
I don't get what's happening, you aren't really starting overtone, just evalueating `(+1 2)` which is illeagal expression, you need space between `+` and 1. Can you start overtone `(use overtone.live)` ?

**Comment by Ex4l** [comment]
That was the space missing, sorry for bothering newbie here.

`user=> (use 'overtone.live)
--> Loading Overtone...

CompilerException java.lang.Exception: Can't connect to native server - no compatible libraries for your system are available: 64-bit windows., compiling:(overtone/live.clj:6:1)
user=>`

Overtone isn't available for 64 bit Windows ?

**Comment by hlolli** [comment]
Overtone is available yes, long story short, you need to install Supercollider yourself and start Overtone with `(use 'overtone.core)` and `(connect-external-server PORT)` or `(boot-external-server)`.
