### ISSUE TITLE
"Unable to locate a valid scsynth executable on your system"

### ISSUE THREAD

**Issue by ganburo** [overtone/overtone#400]
This happens every time I try and boot up a new external server. I'm running a 64 bit windows environment. I have no idea why, I've followed all of the directions. My scsynth.exe is sitting in its program folder.

![sad](https://user-images.githubusercontent.com/16140233/33242622-02cb12ae-d2a6-11e7-8e38-fa19bd2c0215.png)
 
I cant connect to a running server either:
![sader](https://user-images.githubusercontent.com/16140233/33242669-a677a106-d2a6-11e7-8fb5-0bc8561cd65c.png)

Any help would be appreciated. 

Thanks!

**Comment by hlolli** [comment]
These supercollider path issues were addressed in last or second last commit, does this also happens when you run Overtone from master branch? If it does work, then I'll hurry up a patch release.

**Comment by ganburo** [comment]
How do I do that? Sorry sort of new to this...

**Comment by hlolli** [comment]
You can either do git clone from your command line, or just download the zip
https://github.com/overtone/overtone/archive/master.zip
extract it, and do the same thing from within that directory as you do here above
