### ISSUE TITLE
OSX: freesound samples make a clicking sound at finish

### ISSUE THREAD

**Issue by jackdreilly** [overtone/overtone#401]
(def kick-d (freesound 41155))
(kick-d)

It sounds fine at first, but always finishes with a clicking sound.

**Comment by jackdreilly** [comment]
Here's an audio recording: https://vocaroo.com/i/s1QSHHb0ehB1

**Comment by hlolli** [comment]
You need to add envelope, try ADSR envelope with short attack and decay and no release time.
```
(adsr attack decay sustain release level curve)
                     :gate gate
                     :action FREE)
```
