### ISSUE TITLE
Unable to resolve symbol: out in this context

### ISSUE THREAD

**Issue by ikzk** [overtone/overtone#408]
```
(require 'overtone.core)
(boot-external-server)
(overtone.core/demo (overtone.core/sin-osc))
```

gives

```
             java.lang.RuntimeException: Unable to resolve symbol: out in this context
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: out in this context, compiling:(null:1:1)
```

**Comment by hlolli** [comment]
Change `:require` to `:use` ?

**Comment by ikzk** [comment]
I'm using https://github.com/boot-clj/boot and with `use` the `ls` function in `overtone.core` namespace will conflict with the `ls` function in `boot.repl` namespace...

**Comment by hlolli** [comment]
ah, that needs to be fixed. Do this `(use '[overtone.core :exclude (ls)])` until we decide what to do with `ls`. Overtone symbols collide a lot with symbols in other libraries actually. But if you're useing Overtone as a library, you should indeed require, but you would then want to boot-internal/boot-external this way
```Clojure
(require '[overtone.core :as ot])
(ot/boot-external-server)
```
or
```Clojure
(require 'overtone.core)
(overtone.core/boot-external-server)
```

**Comment by ikzk** [comment]
Oh you are right. Indeed the command I run was `(overtone.core/boot-external-server)`, sorry for the typo.

To me the name of `ls` is okay, but we need overtone working with `require`. (Maybe the reason why I got that `unable to resolve symbol` error is overtone uses `quote` instead of `quasiquote` in the macro definitions? Just my guess)

**Comment by hlolli** [comment]
Yes, you're indeed right!
```
(meta #'overtone.core/out)
{:doc "\n  write a signal to a bus, adding to previous contents. \n\n  [bus :none, signals :none]\n\n  bus     - The index of the buss to write to. The \n            lowest index numbers are written to \n            the audio hardware. \n  signals - A list of signals or single output to \n            write out. You cannot change the size \n            of this once a synth has been defined. \n\n  Write a signal to a bus, adding to any existing contents\n\n  N.B. Out is subject to control rate jitter. Where sample \n  accurate output is needed, use OffsetOut.\n\n  When using an array of bus indexes, the channel array will \n  just be copied to each bus index in the array. So (out:ar \n  [bus1 bus2] channels-array) will be the same as (+ (out:ar \n  bus1 channelsArray) (out:ar bus2 channelsArray)). \n\n  Categories: \n  Rates: [ :ar, :kr ]\n  Default rate: :auto", :arglists ([bus signals]), :name out, :ns #object[clojure.lang.Namespace 0x49312891 "overtone.core"], :orig-ns overtone.sc.ugens}
```
the symbol is indeed there. I'm guessing the demo macro, as it provides an `out` bus. Let me check...

**Comment by hlolli** [comment]
That was an easy fix, are you on git master? Could you test my changes?

**Comment by ikzk** [comment]
Thanks! Let me try now!

**Comment by ikzk** [comment]
I can confirm no exception is thrown now. Thanks!

**Comment by hlolli** [comment]
Very good!

And since you're on master, I really need more people testing `boot-internal-synth`, when you have time, could you try the internal synth and tell me if you encounter any problems?

**Comment by ikzk** [comment]
Sure I'll definitely report any problems I find! (Thanks again for your work
