### ISSUE TITLE
SuperCollider not installed? Unable to use `overtone.live`

### ISSUE THREAD

**Issue by oliv9286** [overtone/overtone#411]
Hi Overtone community,
I followed the instructions to start a clojure project and added overtone as a dependency to my `project.clj`. I did `lein deps` and started the REPL. 

However after I do `(use 'overtone.live)`, I'm getting the following error, then the REPL gets disconnected on its own. I checked the `~/Library/Application Support/` path, and turns out SuperCollider is not present, am I missing something in the installation process? Do I need to be installing SuperCollider apart from Overtone? 

```Found 0 LADSPA plugins 
*** ERROR: open directory failed '/Users/<username>/Library/Application Support/SuperCollider/synthdefs'
Number of Devices: 6
   0 : "MDR-1000X"
   1 : "MDR-1000X"
   2 : "Built-in Microph"
   3 : "Built-in Output"
   4 : "DisplayPort"
   5 : "ZoomAudioDevice"

input and output sample rates do not match. 16000 != 44100
could not initialize audio.```

Cheers

**Comment by hlolli** [comment]
I'm not on Machintosh, but to answer the question of wether Supercollider needs to be installed, the answer is no it shouldn't need to be.

The 16000Hz sampling rate is probably a setting from your microphone, could you check if you can configure the sampling rate of your microphones in Audio MIDI Setup?

**Comment by oliv9286** [comment]
I changed the microphone sample rate and overtone is now starting correctly, many thanks for the help!
