### ISSUE TITLE
Syntax error with Clojure 1.10

### ISSUE THREAD

**Issue by newkozlukov** [overtone/overtone#422]
`(use 'overtone.live)` fails with syntax error on clojure "1.10.0". No such thing with "1.9.0" and below.

Steps:

1. Install `clojure` package from archlinux repo or create leiningen project with `[org.clojure/clojure "1.10.0"]` as dependency
2. Add overtone "0.10.3" as dependency
3. Enter `(use 'overtone.live)`

Output:
```nREPL server started on port 43755 on host 127.0.0.1 - nrepl://127.0.0.1:43755
REPL-y 0.4.3, nREPL 0.5.3
Clojure 1.10.0
OpenJDK 64-Bit Server VM 10.0.2+13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

tryovertone.core=> (use 'overtone.live)
--> Loading Overtone...

tryovertone.core=> Syntax error macroexpanding clojure.core/ns at (app_icon.clj:1:1).
() - failed: Insufficient input at: [:ns-clauses :import :classes :package-list :classes] spec: :clojure.core.specs.alpha/package-list
[java.awt.Toolkit] - failed: simple-symbol? at: [:ns-clauses :import :classes :class] spec: :clojure.core.specs.alpha/import-list
:import - failed: #{:refer-clojure} at: [:ns-clauses :refer-clojure :clause] spec: :clojure.core.specs.alpha/ns-refer-clojure
:import - failed: #{:require} at: [:ns-clauses :require :clause] spec: :clojure.core.specs.alpha/ns-require
:import - failed: #{:use} at: [:ns-clauses :use :clause] spec: :clojure.core.specs.alpha/ns-use
:import - failed: #{:refer} at: [:ns-clauses :refer :clause] spec: :clojure.core.specs.alpha/ns-refer
:import - failed: #{:load} at: [:ns-clauses :load :clause] spec: :clojure.core.specs.alpha/ns-load
:import - failed: #{:gen-class} at: [:ns-clauses :gen-class :clause] spec: :clojure.core.specs.alpha/ns-gen-class```

**Comment by hlolli** [comment]
Can you confirm that the merge from @ooesili fixes it?

**Comment by cicerojones** [comment]
Afraid I was still getting an error, but, after looking over the pull request, I noticed that the offending `:import` statement _with_ the vector literal was still in my code. 

So I hackily went into my `~/.m2/repository/overtone/overtone/0.10.3/overtone-0.10.3.jar:overtone/libs/app_icon.clj` and changed it by hand to the updated syntax in the commit and all was well.

So, I guess `lein deps` is not getting the updated version? Am I doing something wrong?

**Comment by hlolli** [comment]
Sorry I still haven't gotten around making a new release, this fix is in pre-release (master branch).
