### ISSUE TITLE
Does overtone work with java 9.0.4

### ISSUE THREAD

**Issue by fractal80y** [overtone/overtone#425]
Hey all, trying to get into overtone for some fun.
csound has been close to me wanting to program music since i was a kid and im sure now they have csound live version now.
I have been following tutorial from both git and documentation and when it comes to (overtone.live) in the repl it just doesnt work and ive had numerous things thrown.

Any tips would be gladly appriciated.

Matt

**Comment by hlolli** [comment]
Could you post the errors that you're getting. I know the jvm options in the leiningen file included in the overtone repo is porbably not portable. And it's already problematic. If you import overtone to a new project tree, the jvm options shouldn't be inherited.

**Comment by hlolli** [comment]
Try now with version 0.10.4, I made some fixes that causes illeagal reflections from Java9 which are treated as errors. I got it running on Java9 in macox Mojave.

**Comment by adamhill** [comment]
FYI. I have Java 12 installed and have not run into any issues yet. (IntelliJ / Cursive environment)

**Comment by hlolli** [comment]
@adamhill thanks for this info!
