### ISSUE TITLE
overtone not working with vim.

### ISSUE THREAD

**Issue by rdtor** [overtone/overtone#426]
Hi i have been triying to compile (demo(sin-osc)) using vim-fireplace,

i get this error, the clojure command runs fine inside the vim and also i can connect to nrepl. i have followed the instruction to setup tutorial project using leinegen and adding overtone dependancy then running lein deps followed by lein repl

 CompilerException java.lang.RuntimeException: Unable to resolve symbol: demo in t
his context, compiling:(tutorial/core.clj:5:1)

**Comment by hlolli** [comment]
It looks like you are either in the wrong namespace, or you haven't done (:use [overtone.live)) in your namespace decleration?

**Comment by rdtor** [comment]
oh i got it to work , i had not saved the file when hittting cpp
