### ISSUE TITLE
ClassCastException for note and chord functions

### ISSUE THREAD

**Issue by mihetare** [overtone/overtone#428]
Hi,

In overtone 0.10.4,  functions such as  (note :c4) or (chord :c4 :minor) give following errors. I tried both Clojure 1.9 and 1.10. I use OpenJDK 64-Bit Server VM 11.0.2+9-Ubuntu-3ubuntu118.04.3.

Execution error (ClassCastException) at overtone.music.pitch/validate-midi-string! (pitch.clj:131).
class java.lang.String cannot be cast to class java.lang.Character (java.lang.String and java.lang.Character are in module java.base of loader 'bootstrap')

Cheers,
Mikael

**Comment by perryprog** [comment]
I'm not sure if this is quite the same issue but I'm still getting problems with this. From what I can tell the change in `note-info` of `Integer.` to `int` causes casts of the octave string to an int to fail.

I'm making a PR that changes the cast to use `Integer/parseInt` which fixes it on my end.
