### ISSUE TITLE
Running an instrument at the repl returns a huge map

### ISSUE THREAD

**Issue by esthl0s** [overtone/overtone#432]
Forgive me if this is rookie user-error, as I'm new to clojure and overtone (though not emacs).
Within emacs, whenever I run an instrument at the repl, the command returns a huge map which effectively breaks the emacs syntax parser for the rest of the repl session. Here's an example of what I mean:
```
user> (demo (sin-osc))
{:synth "user/audition-synth",
 :id 33,
 :target 7,
 :position :tail,
 :args {},
 :sdef
 {:name "user/audition-synth",
  :constants [0.0 2.0 1.0 440.0 0.01],
  :params (),
  :pnames (),
  :ugens
  ({:id 295,
    :name "SinOsc",
    :rate 2,
    :rate-name :ar,
    :special 0,
    :args (440.0 0.0 1.0 0.0),
    :n-outputs 1,
    :spec
    {:args
```

This goes on for quite a while. Note that the sound still plays. Any ideas?

**Comment by hlolli** [comment]
That is strange indeed. Are you using Cider with emacs? It seems that the clojure printer is doing something it shouldn't.

What should happen is
```
user=> (demo (sin-osc))
#<synth-node[loading]: user/audition-synth 33>
```

But if we sequence the return value of demo, which is synth-node, we get
```
([:synth "user/audition-synth"] [:id 34] [:target 7] [:position :tail] [:args {}] [:sdef {:name "user/audition-synth", :constants [0.0 2.0 1.0 440.0 0.01], :params (), :pnames (), :ugens (#<sc-ugen: trig:kr [0]> #<sc-ugen: linen:kr [1]> #<sc-ugen: sin-osc:ar [0]> #<sc-ugen: binary-op-u-gen:ar [3]> #<sc-ugen: out:ar [4]>)}] [:status #object[clojure.lang.Atom 0x7d70c2f6 {:status :ready, :val :live}]] [:loaded? #object[clojure.core$promise$reify__8486 0x7c85f2e6 {:status :ready, :val true}]])
```

Can you tell me which version of Overtone you are using, and which version of Cider (if Cider)?

To bypass this in a crude way, you could force a different return value, like
(do (demo (sin-osc)) nil)

**Comment by alxdb** [comment]
I'm also having this issue. cider version 0.22.0, overtone version 0.10.6

**Comment by simon-katz** [comment]
I get the huge map when pretty printing is turned on, but not when it is turned off.

For something defined with `definst`, you can change the output with something like the method definition below (but you probably want to print more detail).

That doesn't help with the `(demo (sin-osc))` example. A method would need to be defined on some other type. Maybe there's a common supertype, so maybe only one method would be needed.

```
(defmethod clojure.pprint/simple-dispatch overtone.studio.inst.Inst [v]
  (clojure.pprint/write "#<overtone.studio.inst.Inst>"))
```

**Comment by hlolli** [comment]
I haven't been able to research it but most likely something is wrong here https://github.com/overtone/overtone/blob/79b671a85fdba68f56ac51d2d4f0bcf521a6b80f/src/overtone/sc/node.clj#L159-L161

if someone has time to see what's going on. But perhaps the print method isn't even called at all, that could indicate a clojure bug.

**Comment by mjgordon** [comment]
Confirming same issue, overtone 0.10.6, cider 0.22.0, nrepl 0.6.0. Adding that emacs usually reports this: 
`error in process filter: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"`
while printing the map. Output is usually long enough to hit a 1mb limit at which point it stops.

**Comment by hlolli** [comment]
This took a while but it's fixed with https://github.com/overtone/overtone/commit/2005bd7c40b8f348d615e61c0687c79143696a2c

Try out the latest changes trough the clojure command line tool by adding this to the deps.edn

```Clojure
{overtone/overtone {:git/url "https://github.com/overtone/overtone.git"
                    :sha "2005bd7c40b8f348d615e61c0687c79143696a2c"}}
```
