### ISSUE TITLE
NOTES map doesn't contain Fb (pitch.clj)

### ISSUE THREAD

**Issue by leearaneta** [overtone/overtone#438]
pretty self-explanatory, we can just add Fb to the notes map

**Comment by leearaneta** [comment]
by the way if we wanted to programmatically convert pitches to midi notes:
```
(defn pitch->midi [pitch]
  (let [pitch (name pitch)
        notes {"C" 0 "D" 2 "E" 4 "F" 5 "G" 7 "A" 9 "B" 11}
        multiplier (if (= \# (last pitch)) 1 -1)]
    (-> (dec (count pitch))
        (* multiplier)
        (+ (notes (clojure.string/upper-case (first pitch))))
        (mod 12))))
```
this would also allow us to work with theoretical keys
for example, g## would be converted to (+ 7 2)

**Comment by hlolli** [comment]
We can add even more note names here when we have the time. The german names are for example missing which use Ces Des Es Fes Ges Geses As Ases etc...
