### ISSUE TITLE
sound only comes from left speaker

### ISSUE THREAD

**Issue by SamuelDiazBidot** [overtone/overtone#441]
Sound only comes from left speaker. The sound is kinda choppy. The same thing happens with headphones.

> --> Loading Overtone...
--> Booting internal SuperCollider server...
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
Found 0 LADSPA plugins
*** ERROR: dlsym load err '/home/sammy/Documents/clojure_work-space/overtone/native/linux/x86_64/libscsynth.so: undefined symbol: load'
*** ERROR: open directory failed '/home/sammy/.local/share/SuperCollider/synthdefs'
playback and capture sample rates do not match (48000 vs. 44100)
Cannot use real-time scheduling (RR/10)(1: Operation not permitted)
AcquireSelfRealTime error
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
Exception in World_OpenUDP: unable to bind udp socket
--> Connecting to internal SuperCollider server...
--> Connection established
JackDriver: max output latency 42.7 ms

**Comment by jsn** [comment]
No idea about choppy (might be "realtime" setting somewhere), but this should be both speakers: `(demo (sin-osc [440 445]))`, see https://github.com/overtone/overtone/wiki/Multi-channel-expansion,-stereo-and-panning

**Comment by hlolli** [comment]
```
JackDriver: client name is 'SuperCollider'
```

This was changed to Overtone some time ago, could you try never version?

Also it looks like Jack is complaining, maybe you start Jack trough qjackctl before starting Overtone (could help).

**Comment by SamuelDiazBidot** [comment]
By starting Jack through qjackctl before Overtone the choppy audio disappeared. I used this command to fix the error: `jackd -r -d alsa -r 44100 -P`. Thanks for the help.
