### ISSUE TITLE
getting an error calling buffer.

### ISSUE THREAD

**Issue by bwanab** [overtone/overtone#444]
I'm following the book: http://overtone.github.io/docs.html. (Really nice!)

In section 3.2.1, this code:
```
(defn generate-sinewave-buffer [len]
  (let [wavetable-vector (mapv (fn [n] (Math/sin (/ (* 2 Math/PI n) len))) (range 0 len))
        empty-buffer     (buffer len)
        wavetable-buffer (buffer-write! empty-buffer wavetable-vector)]
    wavetable-buffer))
```
Gives an error. I traced it to 
```
(buffer 1024)
Execution error (NullPointerException) at overtone.sc.buffer/assert-less-than-max-buffers (buffer.clj:67).
null
```

**Comment by hlolli** [comment]
Could it be that you really filled the :max-buffers value? You would have needed to have created 1024 buffers. You can increase this with

```Clojure
:sc-args {:max-buffers 8192},
```

in your config (probably ~/.overtone/config.clj)

The error message could have been better, at least better than random errors that was appearing before I added this assertion.

**Comment by bwanab** [comment]
setting {:max-buffers 8192} worked. Thanks again.

**Comment by plexus** [comment]
Thank you for the report!
