### ISSUE TITLE
Unable to locate package openjdk-6-jdk

### ISSUE THREAD

**Issue by vikrantsingh47** [overtone/overtone#451]
to install , i ran this command: sudo apt-get install jack-tools ant openjdk-6-jdk fftw3 qjackctl

but I am getting the error: Unable to locate package openjdk-6-jdk

**Comment by hlolli** [comment]
openjdk-6 is very old. Try to use newer version

**Comment by rogerallen** [comment]
@vikrantsingh47 must've been following the instructions on https://github.com/overtone/overtone/wiki/Installing-and-starting-jack

**Comment by hlolli** [comment]
I just updated the wiki (closing)
