### ISSUE TITLE
API change in tools.deps

### ISSUE THREAD

**Issue by puredanger** [overtone/overtone#456]
Just wanted to drop a note that the newest version of tools.deps.alpha contains some api changes (moving towards getting out of alpha). So when you bump to tools.deps.alpha >= 0.9.745, your use of `clojure.tools.deps.alpha.reader` in `src/overtone/jna_path.clj` needs to be updated - same function `slurp-deps` exists, but is now in `clojure.tools.deps.alpha` instead so just need to update the ns requires.

**Comment by hlolli** [comment]
This has been accounted for, thanks for the api-change heads-up!
