### ISSUE TITLE
Example `clapping_music.clj` Freesound download fails

### ISSUE THREAD

**Issue by bkushigian** [overtone/overtone#463]
When I try to run `overtone.examples.compositions.clapping-music` I get
```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling clapping_music.clj at (9:12)
   #:clojure.error{:phase :execution,
                   :line 9,
                   :column 12,
                   :source "clapping_music.clj"}
             Compiler.java: 3707  clojure.lang.Compiler$InvokeExpr/eval
             Compiler.java:  457  clojure.lang.Compiler$DefExpr/eval
             Compiler.java: 7182  clojure.lang.Compiler/eval
             Compiler.java: 7636  clojure.lang.Compiler/load
                      REPL:    1  overtone.examples.compositions.bells/eval34007
                      REPL:    1  overtone.examples.compositions.bells/eval34007
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7132  clojure.lang.Compiler/eval
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
    interruptible_eval.clj:   91  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  665  clojure.core/apply
                  core.clj:  660  clojure.core/apply
                regrow.clj:   20  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  155  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  190  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  189  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  748  java.lang.Thread/run

1. Caused by java.lang.Exception
   Aborting! Download failed. File not found:
   https://www.freesound.org/apiv2/sounds/132676/?format=json
```

Going to `https://freesound.org/apiv2/sounds/132676/` I see that there is no sound registered there. I'm guessing it was removed at some point?

**Comment by harold** [comment]
Hi, original author of `clapping_music.clj` here.

That's a mild bummer. Looks like the sound was deleted:
![image](https://user-images.githubusercontent.com/7443/99131854-7bc78d00-25d1-11eb-94b0-e3cd2fef80f3.png)

Any clap will do. Maybe try this one:
 - https://freesound.org/people/NoiseCollector/sounds/3718/

**Comment by harold** [comment]
Eight years ago (!) - and look at this clever nonsense, ha!
 - https://github.com/overtone/overtone/commit/616e2a871b6d15e55c57fa048da19e487734057e#diff-f15b8d19a1104ae2b277d0ab1ef9e1531012c0f13fbe05482472633c92697255R16-R19

**Comment by bkushigian** [comment]
Oh cool, looking forward to hearing it work! 

I've tried a few other claps but I couldn't get any sound. Upon further inspection it looks like there have been a change in argument order to the playable samples returned by `freesound`. For instance,
`(clap 1 0 0 (* v 0.33)))` plays from time 0 to time 0, and what appears to be the velocity argument is passed in to an argument that does something I don't understand.

**Comment by bkushigian** [comment]
Re: Clever nonsense: definitely loving it!

**Comment by harold** [comment]
Ha! Very interesting investigations on your part. Did you ever get it to play?

Are you a fan of Reich? I've learned a lot since writing that program, including reading this essay (https://ccnmtl.columbia.edu/draft/ben/feld/mod1/readings/reich.html) and the rest of his book, "Writings on Music". 

I am still into minimalism and generative art (visual and music), and I now believe that he might not appreciate this kind of mechanization. But I find many of his (and other's) compositions super-inspiring, and to this day maintain that there is a wide open field of mechanized minimalism to be explored.

Stay rad.

**Comment by plexus** [comment]
Thanks for fixing this!
