### ISSUE TITLE
clapping music example uses bad arguments

### ISSUE THREAD

**Issue by bkushigian** [overtone/overtone#465]
I'm guessing this is due to an API change. The `clap` function, which is defined as: `(def clap (freesound 48310))`, is later called with `(clap 1 0 0 (* v 0.33))`, where `v` is supposed to be the velocity. The two `0` arguments correspond to start and end position in the sample, and since start = end, none of the sample is actually played.

This should be fixed to `(clap 1 0 1 0 (* v 0.33))`.

**Comment by plexus** [comment]
Thanks for the patch!
