### ISSUE TITLE
New release and "Must hint overloaded method: toArray" when using overtone 0.10.6 with leiningen and JDK 14

### ISSUE THREAD

**Issue by jumarko** [overtone/overtone#473]
It seems it's worth to make a new release after a while - these are the changes since the last 0.10.6 release: https://github.com/overtone/overtone/compare/799dbdbf566b2e226178ad0ddd61ca415e5306cf...master

In particular when I use 0.10.6 in my project I get this error - I'm running with Leiningen 2.9.5 and JDK 14:
```
lein -v
...
Leiningen 2.9.5 on Java 14.0.1 OpenJDK 64-Bit Server VM
```

```
lein repl
...
Exception in thread "main" Syntax error compiling deftype* at (clojure/core/rrb_vector/rrbt.clj:282:1).
...
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray
```

This is a well-known issue with JDK 11+ and has been fixed in core.rrb-vector: https://ask.clojure.org/index.php/6866/core-rrb-vector-fails-on-jdk-11-ea-builds
When I cloned the new repo it seems to have much less dependencies than the old version and also some dependencies have been updated so I guess the issue is automatically resolved.

**Comment by plexus** [comment]
Thanks for reporting this @jumarko , there have been three releases in the last two months, so I think this has been resolved.
