### ISSUE TITLE
can the owner of this repo make a release to clojar?

### ISSUE THREAD

**Issue by gzmask** [overtone/overtone#483]
Clojar's release version and the master branch is off by a lot now, a few bugs that's fixed at not released.

**Comment by pfeodrippe** [comment]
@samaaron @hlolli Am I able to publish a new release? How do you normally do it?

**Comment by hlolli** [comment]
I'd say, let's stick with clj.deps and try to make an uberjar pipeline. I believe Sam gave me access to clojars but I never got around releaseing there. That's why I've been recommending clj.deps over leiningen. But I believe both can work with a plugin. But we can do it for sure, release on clojars.

**Comment by pfeodrippe** [comment]
> I'd say, let's stick with clj.deps and try to make an uberjar pipeline. I believe Sam gave me access to clojars but I never got around releaseing there. That's why I've been recommending clj.deps over leiningen. But I believe both can work with a plugin. But we can do it for sure, release on clojars.

Great! Let’s try to do it manually first, document it and then we can automate the steps, let me know if you want to schedule it or if I would be able to do this one (you would have to pass me some credentials).

**Comment by plexus** [comment]
hey @hlolli @pfeodrippe @samaaron, looks like a release didn't happen after all?

We've been discussing Overtone on Clojurians, and there's interest from multiple people to give it some fresh attention and maintenance. At a minimum releasing what is here would be a good start, for me the current version on Clojars simply doesn't work, which quite unfortunate, since most people will probably still first try to run off clojars.

@pfeodrippe has commit access here, but does not have deploy rights to Clojars. Would it be possible for him or me (or both) to be added to the overtone group on Clojars so we can start pushing new releases again?

**Comment by pfeodrippe** [comment]
@samaaron @hlolli I guess @plexus is pretty trustworthy, let me know if you can give him commit and clojars access \o

**Comment by eval-on-point** [comment]
> hey @hlolli @pfeodrippe @samaaron, looks like a release didn't happen after all?
> 
> 
> 
> We've been discussing Overtone on Clojurians, and there's interest from multiple people to give it some fresh attention and maintenance. At a minimum releasing what is here would be a good start, for me the current version on Clojars simply doesn't work, which quite unfortunate, since most people will probably still first try to run off clojars.
> 
> 
> 
> @pfeodrippe has commit access here, but does not have deploy rights to Clojars. Would it be possible for him or me (or both) to be added to the overtone group on Clojars so we can start pushing new releases again?

Out of curiosity, can you post a link to said discussion?

**Comment by plexus** [comment]
Thanks @samaaron (I guess it was you) for giving me repo access. I will use it wisely :)

That still leaves the question of who can help us get a release out. There are four people with access to the [overtone group on clojars]: 

* [hlolli](https://clojars.org/users/hlolli)
* [mozinator](https://clojars.org/users/mozinator)
* [rosejn](https://clojars.org/users/rosejn)
* [samaaron](https://clojars.org/users/samaaron)

So apart from Sam and Jeff it's only @hlolli and @mozinator. Would either of you be willing to work with us on this? Maybe get us a release key so we can automate the deployments from CI? I don't normally care too much about CI deployments, but in this case it would remove the need to have someone with clojars access in the loop for future releases. 

> Out of curiosity, can you post a link to said discussion?

@eval-on-point check the recent history of the #overtone channel, it should be easy to find.

**Comment by samaaron** [comment]
Hiya @plexus - yep it was me :-)

I've also added you as an admin over on Clojars. Let me know if you need anything else.

Thanks so much for caring about Overtone x

**Comment by plexus** [comment]
Thank you so much! This is great.

Like I said on slack, I have limited bandwidth and don't plan on becoming "the overtone maintainer", but it seems there are still a bunch of people around who care about overtone, so I hope to facilitate things as well as I can, so the project can stay relevant.

Overtone is what really got my hooked on Clojure so many years ago, and I still think it's a fantastic piece of kit. Thank you and Jeff for putting it out here for folks to have fun with and get creative.

**Comment by plexus** [comment]
Just noticed I'm a member of the Overtone org now, but I don't actually have write access here it seems... so I can't merge PRs or close issues. @samaaron sorry to keep bothering you with this, but could you have a look at that? Thank you!

**Comment by samaaron** [comment]
@plexus ooh, I hadn't realised that - hopefully this has now been resolved...

**Comment by plexus** [comment]
Yes! looks good now, thank you so much! I'm going to try to release what's on master today to establish a new baseline, and then we can take it from there.

One last thing @samaaron , I posted to the Overtone mailing list (https://groups.google.com/g/overtone) but my post is "pending approval". Could you look at that, and maybe give me admin access there as well, so I can help approve future posts?

Thank you! :notes:

**Comment by samaaron** [comment]
Ace - amazing work. Thanks so much for breathing life into the old beast.

I've approved your mailing list email and also added you as a "Manager". Hopefully that means you're all set there too.

Thanks once again!

**Comment by plexus** [comment]
Overtone 0.11.0 is out, so I think we can close this. Thanks everyone!

https://groups.google.com/g/overtone/c/fl3yDfyLN7w
