### ISSUE TITLE
"Unresolved symbol" errors highlights, explicit linter support required?

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [overtone/overtone#485]
Due to the way Overtone merges and exports its API symbols in the `overtone.live` namespace, linters seem unable to follow and the result is that every symbol used is error-highlighted as an "Unresolved symbol" - at least in Doom Emacs, which is based upon `clojure-lsp` and `clj-kondo`.

Is there a different way to have the same namespace merging effect in a way that linters could keep track of? 

Alternatively, someone mentioned that `clj-kondo` can be given a config to enable support for this sort of thing, but I wouldn't know how to go about doing that.

**Comment by wildwestrom** [comment]
Yep, I'd love to see a workaround so that linters can tell what is going on.

**Comment by pfeodrippe** [comment]
@monkey-w1n5t0n @wildwestrom Support for `clj-kondo` was added, let me know if it improves your workflow o/

**Comment by wildwestrom** [comment]
Woohoo!
