### ISSUE TITLE
Compile supercollider to a newer version (v3.11.2, at least)

### ISSUE THREAD

**Issue by pfeodrippe** [overtone/overtone#491]
How to update SC?

In OSX, there were some issues with CoreAudio where the scheduling was unstable (https://github.com/supercollider/supercollider/issues/5168), it was fixed at v3.11.2 (https://github.com/supercollider/supercollider/pull/5358), while we use scsynth v3.10.2 (https://github.com/overtone/scsynth).

Hopefully, it would fix https://github.com/overtone/overtone/issues/480.

@hlolli I see that we have https://github.com/overtone/scsynth, do you have any instructions on how to compile it for OSX (later I will check how to do this for Windows and Linux)?

**Comment by plexus** [comment]
We no longer package supercollider ourselves, so this can be closed.
