### ISSUE TITLE
Add CI to publish to Clojars automatically (Github actions)

### ISSUE THREAD

**Issue by pfeodrippe** [overtone/overtone#492]
When committing to `master`, publish a patched version to Clojars.

We could create a `version` file containing the major and minor parts, e.g. `0.10`, the patch would be automatically incremented (we are now in `0.10.6`, so it would be `0.10.7`). For breaking changes, we would increment the `version` file (e.g. `0.11`) and the patch would start from there, e.g. `0.11.0`).

**Comment by plexus** [comment]
Overtone now uses the same release process that Lambda Island libraries use. Releasing is done by invoking `bin/proj release`, which does a bunch of things, like updating the CHANGELOG, creating a Github release, updating versions in the README, etc.

Versioning is now also lambdaisland style, with the minor version incrementing for each release, and the teeny version reflecting the number of commits.

I think this is good enough, and we can run like this for a good long time, so I'll close this ticket.
