### ISSUE TITLE
overtone.inst.synth fails to load on clojure 1.11

### ISSUE THREAD

**Issue by yuhan0** [overtone/overtone#494]
To reproduce, start a repl with clojure 1.11

```clj 
;;deps.edn 
{:deps {org.clojure/clojure {:mvn/version 1.11.1} 
        overtone/overtone {:mvn/version "0.10.6"}}
```
```clj
(ns repro 
  (:use [overtone.live] 
        [overtone.inst.synth]))
```
This fails to load with the error message:
```
=> Execution error (ClassCastException) at overtone.sc.machinery.ugen.fn_gen$mk_multi_ugen_fn$fn__13392/doInvoke (fn_gen.clj:281).
  class clojure.lang.LazySeq cannot be cast to class java.lang.Number clojure.lang.LazySeq is in unnamed module of loader 'app'; java.lang.Number is in module java.base of loader 'bootstrap')
```

On further inspection the cause is the use of `abs` in this definst, which in clojure 1.11 collides with the newly introduced `clojure.core/abs`.
https://github.com/overtone/overtone/blob/c146d057a977e8fa1977d550066d6afd924949de/src/overtone/inst/synth.clj#L146
It appears that within the `definst` context, the symbol is conditionally substituted with an autogenerated var `overtone.sc.ugen-collide/abs` according to some macromagic analysis of the callsite:
```
  This ugen's name collides with the existing fn 
  #'clojure.core/abs. When calling this fn within a synth 
  definition, #'clojure.core/abs will be called unless the 
  argument list suggests that this is a ugen call. 
  overtone.sc.ugen-collide/abs will therefore only be called 
  if the arg list is a single map or at least one of the 
  args is a ugen and the rest consist only of numbers, 
  sequentials, keywords and other ugens. 
```

I extracted the offending call and shrank it to the following - note that the error only occurs with multi-channel expansion, eg. (saw [freq1 freq2]) , which returns a seq of ugens that apparently didn't satisfy the overloading criteria.
```clj
(ns repro
  (:require
   [overtone.live] ; side effects
   [overtone.sc.ugens :as ugens]
   [overtone.studio.inst :refer [definst]]))

(definst minimal []
  (let [src (ugens/saw [440 441])]
    (abs src)))
```

Some context: I'm completely new to the library and immediately encountered this issue with the first tutorial examples in https://savo.rocks/posts/starting-your-computer-music-journey-with-clojure-and-overtone-in-emacs/.

**Comment by plexus** [comment]
This is fixed on master now, we had to mark `abs` as a numeric function, to improve the heuristics for when it is considered a ugen.

Generally you can also work around these kind of issues by adding `:force-ugen` -> `(abs src :force-ugen)`.

Sorry for the incovenience! We should have this released before long.
