### ISSUE TITLE
Cannot run `(use 'overtone.live)`

### ISSUE THREAD

**Issue by alejandrosame** [overtone/overtone#497]
Clojure and OpenJDK versions:
```
Clojure 1.11.1
OpenJDK 64-Bit Server VM 19.0.1+10-nixos
```

Trying to evaluate `(use 'overtone.live)` leads to the following error:

```
--> Booting internal SuperCollider server...
Execution error (IllegalArgumentException) at overtone.libs.deps/wait-until-deps-satisfied (deps.clj:187).
No matching method sleep found taking 1 args
```

I'm unable to find such sleep method, my guess is the `Thread/sleep` methods that I can see on the overtone codebase. It's also hard to figure out the last environment known to work with jars before they are uploaded to `clojars`. Having CI actions (#492) could help with this issue.

For completion, here's the full log:
```
$ lein repl
nREPL server started on port 41475 on host 127.0.0.1 - nrepl://127.0.0.1:41475
REPL-y 0.5.1, nREPL 1.0.0
Clojure 1.11.1
OpenJDK 64-Bit Server VM 19.0.1+10-nixos
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

new-overtone-playground.core=> (use 'overtone.live)
--> Loading Overtone...
SC FFT global init: cosTable initialised.
WARNING: abs already refers to: #'clojure.core/abs in namespace: overtone.sc.vbap, being replaced by: #'overtone.sc.vbap/abs
  ********************************************************** 
       WARNING: JVM argument TieredStopAtLevel=1 is active, and may 
       lead to reduced performance. This happens to currently be the 
       default lein setting:

       https://github.com/technomancy/leiningen/pull/1230

       If you didn't intend this JVM arg to be specified, you can turn 
       it off in your project.clj file or your global 
       ~/.lein/profiles.clj file by adding the key-val

       :jvm-opts ^:replace [] 
       ********************************************************** 
--> Booting internal SuperCollider server...
Execution error (IllegalArgumentException) at overtone.libs.deps/wait-until-deps-satisfied (deps.clj:187).
No matching method sleep found taking 1 args

JackDriver: client name is 'Overtone'
SC_AudioDriver: sample rate = 48000,000000, driver's block size = 1024
JackDriver: max output latency 21,3 ms
Exception in World_OpenUDP: bind: Address already in use
--> Connecting to internal SuperCollider server...
new-overtone-playground.core=> --> Connection established
JackDriver: max output latency 42,7 ms


new-overtone-playground.core=> 
```

**Comment by soulflyer** [comment]
I'm seeing the same warning trying to (use 'overtone.core) 
It doesn't appear to stop the connection to the server from working though...
```
overtone-play.core> (boot-external-server)
--> Booting external SuperCollider server...
--> Connecting to external SuperCollider server: 127.0.0.1:2557
--> Connection established
Execution error (IllegalArgumentException) at overtone.libs.deps/wait-until-deps-satisfied (deps.clj:187).
No matching method sleep found taking 1 args
overtone-play.core> (definst foo [] (saw 220))
#<instrument: foo>
overtone-play.core> (foo)
```

**Comment by soulflyer** [comment]
If I change line 181 and 187 in deps.clj like this:
`(Thread/sleep wait-time 0)`
The error message goes away. Not certain, but it looks like the java wait fn now expects 2 params instead of 1, and adding that 0 keeps it happy. There may be other consequences, I haven't had chance to test it properly but this may get you moving again.

**Comment by soulflyer** [comment]
Proceed with caution, there are Thread/sleep calls all over the place. Maybe rolling back to an older version of java will work. @alejandrosame what version are you using? Mine is 19.0.2

**Comment by alejandrosame** [comment]
@soulflyer The previous example was under 19.0.1. I think I had the same issue with Java 17. I'll do some more checking, thanks!

**Comment by alejandrosame** [comment]
I think I found the issue. The `leiningen` package I'm using is linked against Java 19, even when I explicitly have Java 17 in the PATH.

```
$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-nixos)
OpenJDK 64-Bit Server VM (build 17.0.5+8-nixos, mixed mode, sharing)

$ lein --version
Leiningen 2.10.0 on Java 19.0.1 OpenJDK 64-Bit Server VM
```

**Comment by soulflyer** [comment]
Stranger and stranger. Thread/sleep with just one parameter works fine with java-19 when called from inside a running overtone.

**Comment by alejandrosame** [comment]
I'm having the impression also that the Clojure code is not inline with the internal `scsynth` provided. I actually managed to make some noise with `openjdk 17`, `supercollider 3.12`, `clojure 1.10.3`, `leiningen 2.10.0` and `overtone 0.10.6`, by running `scsynth` separately and then within `lein repl` doing `(connect-external-server 57110)`.

Leaving for reference the project where I'm doing my testing, although it's currently in a messy state: https://git.sr.ht/~alejandrosame/new-overtone-playground/tree

I'll start looking soonish into CI for this project, just within Linux and NixOS it's becoming quite challenging to keep up with the exact combination of versions that work within the stack.

**Comment by soulflyer** [comment]
I think you are right. I also had some success with an external server started with `(boot-external-server)`. 
`openjdk 19.0.2 2023-01-17`,  `SuperCollider 3.13.0-rc2`, `clojure 1.10.1`, `Leiningen 2.10.0` and overtone running directly from the current master branch. This is on an M1 mac.

Now having a look at what might be involved in getting the internal scsynth working again. It will involve some changes to the system detection code. Since it was written apple have invented a whole new processor which doesn't seem to like the old x86 native code that overtone thinks it needs.

As for keeping up with working versions, I can help on the mac side and to some extent linux.

**Comment by olaven** [comment]
> I was able to fix this by changing this function in the overtone.libs.deps namespace:
> ....

I'm a beginner to both Overtone and Clojure, so pleas excuse me if this is noise. I was able to get past the initial error when applying this change, but I am still crashing with the following: 
```bash
java.lang.UnsatisfiedLinkError: Can't load library: /Users/olavsundfor/Library/Caches/JNA/temp/jna6327135372627260178.tmp
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2011)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at overtone.sc.machinery.server.native$eval9819$fn__9820$fn__9828.invoke(native.clj:39)
	at clj_native.direct$loadlib.invokeStatic(direct.clj:147)
	at clj_native.direct$loadlib.invoke(direct.clj:143)
	at overtone.sc.machinery.server.native$eval9819$fn__9820.invoke(native.clj:179)
	at overtone.sc.machinery.server.native$eval9819.invokeStatic(native.clj:37)
	at overtone.sc.machinery.server.native$eval9819.invoke(native.clj:36)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
        ...
```

I am using `openjdk@19`, `overtone@0.10.6` and Clojure `1.11.1`, and I'm on mac os with an M2 chip.

**Comment by stathissideris** [comment]
@olaven looks like one of the native libaries could not be loaded. How did you apply the change I suggested?

**Comment by olaven** [comment]
@stathissideris I cloned overtone, applied the modification and added a symlink to the overtone folder in `my-project/checkouts`. I was able to add some `println`-calls and see the output, so I believe that part worked ☺️

**Comment by olaven** [comment]
@stathissideris I guess https://github.com/overtone/overtone/issues/499 is the actual underlying issue for me and that my comments are likely irrelevant for this issue.

**Comment by MitchellJThomas** [comment]
On a Intel Core i7 Macbook Pro running MacOS 13.5.2 (22G91) using Java 21 I also ran into the same error.  I fixed it by switching to Java 17.  Specifically 
`(Runtime/version)
#object[java.lang.Runtime$Version 0x699b771a "17-ea+12"]`

**Comment by plexus** [comment]
I've applied @stathissideris proposed change, as this seems to fix the originally reported error with Thread/sleep not resolving correctly. Thanks for figuring that out!

@olaven if you have trouble with the native libraries your best option is to install supercollider manually and then use `(boot-external-server)`, or start it yourself and `(connect-external-server)`. Sorry for the hassle.
