### ISSUE TITLE
Apple M1/2 Arm64 support

### ISSUE THREAD

**Issue by dmg46664** [overtone/overtone#499]
There are probably several issues but the first to appear is 

```
Warning: failed to load the S3TransporterFactory class
java.lang.UnsatisfiedLinkError: Unable to load library 'scsynth':
dlopen(/Users/dmg46664/projects/test/native/macosx/x86_64/libscsynth.dylib, 0x0009): tried: '/Users/dmg46664/projects/test/native/macosx/x86_64/libscsynth.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dmg46664/projects/test/native/macosx/x86_64/libscsynth.dylib' (no such file), '/Users/dmg46664/projects/test/native/macosx/x86_64/libscsynth.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I don't think any ARM64 binaries are catered for by this code:
https://github.com/overtone/overtone/blob/master/src/overtone/jna_path.clj

**Comment by diegovdc** [comment]
That's true, hadn't realized it because I always connect to an external server.

**Comment by plexus** [comment]
Overtone tries to work out of the box by packaging its own build of supercollider as a library, but there are a number of reasons why that might not work for a given situation. In that case you should install SuperCollider yourself, and use `(boot-external-server)` or `(connect-external-server)`. 

You can find precompiled binaries here: https://github.com/SuperCollider/SuperCollider/releases

Package managers like Homebrew should also have supercollider available. You only really need the server component, i.e. the `scsynth` command.

**Comment by plexus** [comment]
I'll leave this issue open as hopefully someday we can offer a M1/2 build out of the box, but it will depend on someone stepping forward who wants to take ownership of that.

**Comment by dmg46664** [comment]
Surely at least the error message can be different, i.e. that M1/x is not supported. This was not a friendly encounter.

**Comment by plexus** [comment]
I'm sorry for your frustrating encounter @dmg46664, I agree that we can be more helpful. Overtone has not had a lot of maintenance or support the last number of years, we're part of a community effort to breathe some new life into it and hopefully make things better going forward. Part of that effort is reviewing old tickets. The embedded supercollider is one of the most common sources of problems, and there's ongoing discussion about how that can be approached differently. Meanwhile we should make it more clear to users that it's not hard and often preferred to run SuperCollider outside of Overtone. Hence why I left some instructions here for the next person on M1/M2 who comes looking for answers.

Feel free to open new issues if you do want to give Overtone another try, or find folks on #overtone on Clojurians slack, or on the [mailing list](https://groups.google.com/g/overtone). Thanks!

**Comment by plexus** [comment]
We dropped the internal supercollder server, it's now up to the user to make sure `scsynth` is available. So as long as there is a supercollider release for a given platform, we should be good.

**Comment by vincentreynaud** [comment]
@plexus really appreciate your suggestions. As someone who's new to the Clojure ecosystem and to Overtone, I'd love a bit more information about the concrete steps to take to ensure the connection with supercollider, which presumably is the issue when encountering the `java.lang.UnsatisfiedLinkError` errors on M1 macs. 

Agree with all the above that this has been a hard one to figure out - and still going. 

I'm encountering this issue event when having supercollider app & server running. What am I missing?

### Context
I have a project using leinungen structured as follows:

`./project.clj`
```clojure
(defproject my-symphony "0.1.0-SNAPSHOT"
  :main ^{:skip-aot true} my-symphony.song
  :jvm-opts ^:replace ["--add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED"]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [overtone "0.10.1"]
                 [leipzig "0.10.0"]])
```

`./src/my_symphony/song.clj`
```clojure
(ns my-symphony.song
  (:require [overtone.core :refer :all]
            [overtone.sc.server :refer [connect-external-server]]
            [leipzig.melody :refer :all]))

; Instruments
(connect-external-server 57110)
(demo 7 (lpf (mix (saw [50 (line 100 1600 5) 101 100.5]))
             (lin-lin (lf-tri (line 2 20 5)) -1 1 400 4000)))
(definst bass [freq 110 volume 1.0]
  (-> (saw freq)
      (* (env-gen (perc 0.1 0.4) :action FREE))
      (* volume)))
```

While I have my separate supercollider app & server running in parallel on port 57110, i run `lein repl` in my overtone project and get this:

```
--> Loading Overtone...
#error {
 :cause /private/var/folders/44/xk39_b516n7b7m9s0x7lh3mh0000gn/T/jna/jna6802615548156225597.tmp: dlopen(/private/var/folders/44/xk39_b516n7b7m9s0x7lh3mh0000gn/T/jna/jna6802615548156225597.tmp, 0x0001): tried: '/private/var/folders/44/xk39_b516n7b7m9s0x7lh3mh0000gn/T/jna/jna6802615548156225597.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64,unknown', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/44/xk39_b516n7b7m9s0x7lh3mh0000gn/T/jna/jna6802615548156225597.tmp' (no such file), '/private/var/folders/44/xk39_b516n7b7m9s0x7lh3mh0000gn/T/jna/jna6802615548156225597.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64,unknown', need 'arm64e' or 'arm64'))
```

**Comment by janwicijowski** [comment]
Hi Vincent,

IIRC overtone tries to connect to a bundled supercollider, which doesn't
have an ARM version, as indicated by the error message. IIRC Overtone
stopped shipping supercollider in the 0.14.3199 version - try upgrading
your version requirements.

sob., 21 wrz 2024 o 14:38 Vincent Reynaud ***@***.***>
napisał(a):

**Comment by plexus** [comment]
Yes, what @janwicijowski said, start by upgrading to the latest Overtone. A lot has been fixed in the past year. Try to avoid reporting issues with old versions, or we'll never be finished.
