### ISSUE TITLE
Not every linux system has jack_lsp

### ISSUE THREAD

**Issue by plexus** [overtone/overtone#508]
Overtone currently shells out to a command line tool to make the jack connections. These are often packaged separately, so they are not available on every system, see also comments in #467 .

This will become even more so with Pipewire becoming the default.

We should at least fail gracefully with a warning message to manually connect your outputs. We could also use JNA jack to do the connections.

**Comment by hlolli** [comment]
Supercollider is usually run with jack on linux, but I don't see why alsa shouldn't also work, even if it doesn't have the same realtime capabilities. If it works on upstream Supercollider, it could be used as fallback if neither jack nor pipewire exists.

**Comment by plexus** [comment]
We now use casa.squid.jack, based on JNA Jack, to make the connections. This also has the benefit that we can ask jack which the physical output ports are, rather than coming up with increasingly intricate regexps to help us guess. So auto-connect should work once again on all linux system, for both PipeWire and Jackd setups, with or without jack_lsp / jack_connect present.
