### ISSUE TITLE
Unable to resolve symbol: ex-message

### ISSUE THREAD

**Issue by stevenleeg** [overtone/overtone#517]
Hi there! I'm trying to get Overtone working on a fresh project but am running into the following error:

```
user=> (use 'overtone.core)
--> Loading Overtone...
CompilerException java.lang.RuntimeException: Unable to resolve symbol: ex-message in this context, compiling:(overtone/sc/machinery/server/connection.clj:110:75)
```

For context, I'm fetching overtone via leiningen and my `project.clj` looks like this:

```
(defproject overtone-tutorial "1.0.0"
  :dependencies [[overtone/overtone "0.13.3177"]]
  :native-path "native"
  :source-paths ["src"])
```

I'm on Fedora 39 with Clojure 1.9.0 and openjdk 17.0.9 2023-10-17. What's strange is that I was able to get an earlier version working (ie I was following the docs and using 0.10.3). It seems like something is either off with my machine or the newer version that's causing this new issue.

Happy to provide any further details that could be helpful in debugging!

**Comment by stevenleeg** [comment]
Wow yup! I updated my `project.clj` to include an explicit Clojure version and everything appears to work as it should:

```clojure
(defproject overtone-tutorial "1.0.0"
  :dependencies [[org.clojure/clojure "1.11.3"]
                 [overtone/overtone "0.13.3177"]]
  :native-path "native"
  :source-paths ["src"])

```

Sorry for dropping an obvious one here but hopefully this'll help others who encounter the same issue down the road :crossed_fingers:.

Cheers!

**Comment by harold** [comment]
Definite no need to apologize. :musical_note: - stay rad.
