### ISSUE TITLE
grunge-bass lacks amp

### ISSUE THREAD

**Issue by jave** [overtone/overtone#523]
the grunge-bass definition declares amp, but its never used.
default amp can be changed to 1, so existing pieces dont change.

add amp in the last multiplier step

(definst grunge-bass
  [note 48 amp 1 dur 0.1 a 0.01 d 0.01 s 0.4 r 0.01]
  (let [freq    (midicps note)
        env     (env-gen (adsr a d s r) (line:kr 1 0 (+ a d dur r 0.1))
                         :action FREE)
        src     (saw [freq (* 0.98 freq) (* 2.015 freq)])
        src     (clip2 (* 1.3 src) 0.9)
        sub     (sin-osc (/ freq 2))
        filt    (resonz (rlpf src (* 8.4 freq) 0.29) (* 2.0 freq) 2.9)
        meat    (ring4 filt sub)
        sliced  (rlpf meat (* 2 freq) 0.1)
        bounced (free-verb sliced 0.8 0.9 0.2)]
    (* amp env bounced)))

**Comment by plexus** [comment]
Fixed on main.

**Comment by jave** [comment]
Awesome!
