### ISSUE TITLE
Multiple vars named `octave-note` imported into `overtone.live`

### ISSUE THREAD

**Issue by frenchy64** [overtone/overtone#528]
There are vars named `octave-note` in `overtone.music.pitch` and `overtone.studio.event`.

I think they are both being interned into `overtone.{core,live}` and one is overwriting the other. The namespace `overtone.examples.notation.mad` doesn't compile because it expected the var from `overtone.music.pitch` but seems to get the one from `overtone.studio.event`.

```clojure
Execution error (ArityException) at overtone.examples.notation.mad/def-notes (mad.clj:55).
Wrong number of args (2) passed to: overtone.studio.event/octave-note
```

**Comment by frenchy64** [comment]
Perhaps `overtone.studio.event/octave-note` should be made private?

**Comment by plexus** [comment]
Thanks for spotting this, yes, it can be private, or named something else.
